### ISSUE TITLE
No Position FeedBack

### ISSUE THREAD

**Issue by TheLoki2020** [Intelligent-Quads/iq_pymavlink_tutorial#1]
Hi,
I was following the youtube series and I'm trying to get the position feedback while using the POSITION_TARGET_GLOBAL_INT.
However no matter what I try to use in the type field in the the_connection.recv_match I do not see anything in the console.
If I change the blocking from true to false the msg I get is None all the time.
I really appreciate any help in this issue.

**Comment by ericjohnson97** [comment]
Sorry for the late response a msg of None indicates that pymavlink did not receive any data. it sounds like the connection is broken. you should check the connection string
